services:
  auth-service:
    build: ./services/auth
    ports:
      - "50051:50051"
    volumes:
      - ./services/auth/internal/config/config.docker.yml:/config.yml
    environment:
      CONFIG_PATH: /config.yml

  auth-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "54321:5432"

  chat-service:
    build: ./services/chat
    ports:
      - "50052:50052"

  chat-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    volumes:
      - ./services/chat/internal/config/config.docker.yml:/config.yml
    ports:
      - "54322:5432"
