name: Build and Test Chat Service

on:
  push:
    paths:
      - "services/chat/**"
  pull_request:
    paths:
      - "services/chat/**"

env:
  REGISTRY: cr.selcloud.ru/golang-course
  IMAGE_NAME: chat-service
  CONTAINER_NAME: chat-service-container

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Test Chat Service
        working-directory: services/chat
        run: |
          go test ./... -timeout 10s

  build-and-push:
    needs: test
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        working-directory: services/chat
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}

      - name: Build and push
        working-directory: services/chat
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag ${{ secrets.REGISTRY }}/$IMAGE_NAME:$TAG_NAME .
